name: C++ Client Release
description: C++ Client Release Process

runs:
  using: composite
  steps:
    - name: Install boost
      uses: ./.github/actions/install-boost
      id: install-boost

    - name: Build Linux Artifacts
      if: runner.os == 'Linux'
      run: |
        ./scripts/build-release.sh launchdarkly-cpp-client
        ./scripts/build-docs.sh libs/client-sdk
      env:
        WORKSPACE: libs/client-sdk

      # Build docs.
      # Attach artifacts to release.

    - name: Build Windows Artifacts
      if: runner.os == 'Windows'
      env:
        OPENSSL_ROOT_DIR: ${{ env.OPENSSL_ROOT_DIR }}
        BOOST_LIBRARY_DIR: 'C:\local\boost_1_81_0\lib64-msvc-14.3'
        BOOST_LIBRARYDIR: 'C:\local\boost_1_81_0\lib64-msvc-14.3'
      # Build binaries.

      # Attach artifacts to release.

    - name: Build Mac Artifacts
      id: brew-action
      if: runner.os == 'macOS'
      run: |
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)" >> "$GITHUB_ENV"
        
        ./scripts/build-release.sh launchdarkly-cpp-client
      env:
        WORKSPACE: libs/client-sdk

      # Attach artifacts to release.