# This is a composite workflow that an generate all the release artifacts
# for the C++ client-side & server-side SDKs.

# This can be ran automatically with the tag_name output from release-please,
# or ran triggered manually with a user provided tag.

name: C++ SDK Release
description: C++ SDK Release Process
inputs:
  tag_name:
    description: 'The tag name of the release to upload artifacts to.'
    required: true
  github_token:
    description: 'The GitHub token to use for uploading artifacts.'
    required: true
  sdk_path:
    description: 'Path to the sdk, e.g. libs/client-sdk.'
    required: true
  sdk_cmake_target:
    description: 'CMake target of the sdk, e.g. launchdarkly-cpp-client.'
outputs:
  hashes-linux:
    description: "base64-encoded sha256 hash of linux build artifacts"
    value: ${{ steps.hash-linux.outputs.hashes-linux }}
  hashes-windows:
    description: "base64-encoded sha256 hash of windows build artifacts"
    value: ${{ steps.hash-windows.outputs.hashes-windows }}
  hashes-macos:
    description: "base64-encoded sha256 hash of macos build artifacts"
    value: ${{ steps.hash-macos.outputs.hashes-macos }}

runs:
  using: composite
  steps:
    - name: Install Ninja
      uses: ./.github/actions/install-ninja
    - name: Install boost
      uses: ./.github/actions/install-boost
      id: install-boost

    - name: Build Linux Artifacts
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get install doxygen
        sudo apt-get install graphviz
        ./scripts/build-release.sh ${{ inputs.sdk_cmake_target }}
        ./scripts/build-docs.sh ${{ inputs.sdk_path }}
      env:
        WORKSPACE: ${{ inputs.sdk_path }}
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Archive Release Linux - GCC/x64/Static
      if: runner.os == 'Linux'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-static/release'
        type: 'zip'
        filename: 'linux-gcc-x64-static.zip'

    - name: Archive Release Linux - GCC/x64/Dynamic
      if: runner.os == 'Linux'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-dynamic/release'
        type: 'zip'
        filename: 'linux-gcc-x64-dynamic.zip'

    - name: Hash Linux Build Artifacts for provenance
      if: runner.os == 'Linux'
      shell: bash
      id: hash-linux
      run: |
        echo "hashes-linux=$(sha256sum linux-gcc-x64-static.zip linux-gcc-x64-dynamic.zip | base64 -w0)" >> "$GITHUB_OUTPUT"

    - name: Upload Linux Build Artifacts
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ls
        gh release upload ${{ inputs.tag_name }} linux-gcc-x64-static.zip linux-gcc-x64-dynamic.zip --clobber
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Publish Documentation
      if: runner.os == 'Linux'
      uses: ./.github/actions/publish-docs
      with:
        workspace_path: ${{ inputs.sdk_path }}

    - name: Configure MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Upgrade OpenSSL
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco upgrade openssl --no-progress
    - name: Determine OpenSSL Installation Directory
      if: runner.os == 'Windows'
      shell: bash
      run: |
        if [ -d "C:\Program Files\OpenSSL-Win64" ]; then
          echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> "$GITHUB_ENV"
        else
          echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL" >> "$GITHUB_ENV"
        fi
    - name: Build Windows Artifacts
      if: runner.os == 'Windows'
      shell: bash
      env:
        OPENSSL_ROOT_DIR: ${{ env.OPENSSL_ROOT_DIR }}
        BOOST_LIBRARY_DIR: 'C:\local\boost_1_81_0\lib64-msvc-14.3'
        BOOST_LIBRARYDIR: 'C:\local\boost_1_81_0\lib64-msvc-14.3'
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: ./scripts/build-windows.sh ${{ inputs.sdk_cmake_target }}

    - name: Archive Release Windows - MSVC/x64/Static
      if: runner.os == 'Windows'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-static/release'
        type: 'zip'
        filename: 'windows-msvc-x64-static.zip'

    - name: Archive Release Windows - MSVC/x64/Dynamic
      if: runner.os == 'Windows'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-dynamic/release'
        type: 'zip'
        filename: 'windows-msvc-x64-dynamic.zip'

    - name: Archive Release Windows - MSVC/x64/Static/Debug
      if: runner.os == 'Windows'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-static-debug/release'
        type: 'zip'
        filename: 'windows-msvc-x64-static-debug.zip'

    - name: Archive Release Windows - MSVC/x64/Dynamic/Debug
      if: runner.os == 'Windows'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-dynamic-debug/release'
        type: 'zip'
        filename: 'windows-msvc-x64-dynamic-debug.zip'

    - name: Hash Windows Build Artifacts for provenance
      if: runner.os == 'Windows'
      shell: bash
      id: hash-windows
      run: |
        echo "hashes-windows=$(sha256sum windows-msvc-x64-static.zip windows-msvc-x64-dynamic.zip windows-msvc-x64-static-debug.zip windows-msvc-x64-dynamic-debug.zip | base64 -w0)" >> "$GITHUB_OUTPUT"

    - name: Upload Windows Build Artifacts
      if: runner.os == 'Windows'
      shell: bash
      run: |
        ls
        gh release upload ${{ inputs.tag_name }} windows-msvc-x64-static.zip windows-msvc-x64-dynamic.zip windows-msvc-x64-static-debug.zip windows-msvc-x64-dynamic-debug.zip --clobber
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Build Mac Artifacts
      id: brew-action
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> "$GITHUB_ENV"
        export OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)
        
        ./scripts/build-release.sh ${{ inputs.sdk_cmake_target }}
      env:
        WORKSPACE: ${{ inputs.sdk_path }}
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Archive Release Mac - AppleClang/x64/Static
      if: runner.os == 'macOS'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-static/release'
        type: 'zip'
        filename: 'mac-clang-x64-static.zip'

    - name: Archive Release Mac - AppleClang/x64/Dynamic
      if: runner.os == 'macOS'
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'build-dynamic/release'
        type: 'zip'
        filename: 'mac-clang-x64-dynamic.zip'

    - name: Hash Mac Build Artifacts for provenance
      if: runner.os == 'macOS'
      shell: bash
      id: hash-macos
      run: |
        echo "hashes-macos=$(shasum -a 256 mac-clang-x64-static.zip mac-clang-x64-dynamic.zip | base64 -b 0)" >> "$GITHUB_OUTPUT"

    - name: Upload Mac Build Artifacts
      if: runner.os == 'macOS'
      shell: bash
      run: |
        ls
        gh release upload ${{ inputs.tag_name }} mac-clang-x64-static.zip mac-clang-x64-dynamic.zip --clobber
      env:
        GH_TOKEN: ${{ inputs.github_token }}
