name: "Hello World Smoke Test"
description: 'Runs the "hello app" for an SDK.'
inputs:
  cmake_target:
    description: 'The name of the CMake target. i.e. hello-cpp-client'
    required: true
  binary_dir:
    description: 'Output directory for the hello world binary'
    required: true


runs:
  using: composite
  steps:
    - name: "Build Hello App"
      shell: bash
      # Should generate a binary in 'inputs.binary_dir'
      run: ./scripts/build.sh ${{ inputs.cmake_target }} OFF
    - name: 'Run Hello App'
      shell: bash
      run: |
        ./${{ inputs.binary_dir }}/${{ inputs.cmake_target}} | tee output.txt
        grep "Please edit" output.txt || (echo "binary did not ask for SDK key as expected" && exit 1) 
