#pragma once

#include <optional>

#include <boost/json/value.hpp>

#include "evaluation_detail.hpp"

namespace launchdarkly {

/**
 * FlagMeta represents an evaluated flag either from the LaunchDarkly service,
 * or in bootstrap data generated by a server SDK.
 */
class FlagMeta {
   public:
    /**
     * The version of the flag.
     */
    uint64_t version() const;

    /**
     * True if a client SDK should track events for this flag.
     */
    bool track_events() const;

    /**
     * True if a client SDK should track reasons for this flag.
     */
    bool track_reason() const;

    /**
     * A timestamp, which if the current time is before, a client SDK
     * should send debug events for the flag.
     * @return
     */
    std::optional<uint64_t> debug_events_until_date() const;

    /**
     * Details of the flags evaluation.
     */
    EvaluationDetail const& detail() const;

    FlagMeta(uint64_t version,
             bool track_events,
             bool track_reason,
             std::optional<long> debug_events_until_date,
             EvaluationDetail detail);

   private:
    uint64_t version_;
    bool track_events_;
    bool track_reason_;
    std::optional<uint64_t> debug_events_until_date_;
    EvaluationDetail detail_;
};

FlagMeta tag_invoke(boost::json::value_to_tag<FlagMeta> const& unused,
                    boost::json::value const& json_value);

}  // namespace launchdarkly
