# This is a composite to allow sharing these steps into other workflows.
# It isn't a shared workflow, because then it isn't convenient to add
# additional package-specific steps.

# The CMake project should follow a convention where the test project is
# gtest_LIBNAME for instance gtest_launchdarkly-cpp-common.
name: Shared CI Workflow
description: 'Shared CI workflow used by C++ packages.'
inputs:
  cmake_target:
    description: 'The name of the CMake target. i.e. launchdarkly-cpp-common'
    required: true
  run_tests:
    description: 'Whether gtest targets should be built & run.'
    required: false
    default: 'true'


runs:
  using: composite
  steps:
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.4
      id: install-boost
      with:
        boost_version: 1.81.0
        platform_version: 22.04
        boost_install_dir: /home/runner/boost
    - name: Build Library
      shell: bash
      run: ./scripts/build.sh ${{ inputs.cmake_target }} ON
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build Tests
      id: build-tests
      if: inputs.run_tests == 'true'
      shell: bash
      run: ./scripts/build.sh gtest_${{ inputs.cmake_target }} ON
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Run Tests
      if: steps.build-tests.outcome == 'success'
      shell: bash
      # This uses the binary, versus "make tests" because the binary
      # has better performance and output.
      run: ./build/gtest_${{ inputs.cmake_target }}
