name: "Server-Sent-Events Contract Tests"
description: 'Runs the SSE test harness against a specified test service.'
inputs:
  test_service_port:
    required: true
    description: "Port of the component under test."
    default: '8123'
  test_harness_port:
    required: false
    description: "Port of the test harness."
    default: '8111'
  debug_logging:
    description: "Whether the test harness should print debug logs for failed tests."
    required: false
    default: 'false'
  extra_params:
    description: "Any other params to be passed to the test harness."
    required: false

runs:
  using: composite
  steps:
    - name: 'Run Test Harness'
      shell: bash
      run: curl -s https://raw.githubusercontent.com/launchdarkly/sse-contract-tests/v2.0.0/downloader/run.sh | bash
      env:
        VERSION: v2
        PARAMS: -url http://localhost:${{ inputs.test_service_port }} -port ${{ inputs.test_harness_port }} ${{ inputs.extra_params }} ${{ inputs.debug_logging == 'true' && '-debug' || '' }} -stop-service-at-end
