  name: Install Ninja
  description: 'Install the Ninja build system.'

  runs:
    using: composite
    steps:
      - name: Install for Ubuntu.
        if: runner.os == 'Linux'
        id: install-ninja-ubuntu
        run: sudo apt install ninja-build

      - name: Install for Mac
        if: runner.os == 'macOS'
        id: install-ninja-mac
        run: brew install ninja

      - name: Install for Windows
        if: runner.os == 'Windows'
        id: install-ninja-mac
        run: choco install ninja