name: "Hello App Smoke Test"
description: 'Runs the "hello app" for an SDK.'
inputs:
  cmake_targets:
    description: 'Space-delimited list of cmake targets'
    required: true
  linkage:
    description: "Must be 'static' or 'dynamic'"
    required: false
    default: 'static'


runs:
  using: composite
  steps:
    - name: "Execute Hello Apps"
      shell: bash
      run: ./scripts/run-hello-apps.sh ${{ inputs.linkage }} ${{ inputs.cmake_targets }}
