name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr-title:
    # https://github.com/launchdarkly/gh-actions/commit/f1760cc538c362c2ab826a3bd22611743ef8f82c
    uses: launchdarkly/gh-actions/.github/workflows/lint-pr-title.yml@f1760cc538c362c2ab826a3bd22611743ef8f82c
