name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint-pr-title:
    # https://github.com/launchdarkly/gh-actions/commit/de4859c8d07c097d573fbcc4bd10b77efed0f5cc
    uses: launchdarkly/gh-actions/.github/workflows/lint-pr-title.yml@de4859c8d07c097d573fbcc4bd10b77efed0f5cc
