# Checks out the tag, builds release builds, and attaches them to the release for the tag.
# If you need to change build scripts, then update the tag to include the modifications.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create release artifacts for.'
        required: true

name: Publish Client Artifacts

jobs:
  release-client:
    strategy:
      matrix:
        # Each of the platforms for which release-artifacts need generated.
        os: [ ubuntu-latest, windows-2022, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - id: release-client
        name: Full release of libs/client-sdk
        uses: ./.github/actions/client-release
        with:
          # The tag of the release to upload artifacts to.
          tag_name: ${{ inputs.tag }}
          github_token: ${{secrets.GITHUB_TOKEN}}
